name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build with production env
        run: |
          # Copy production env file to .env
          cp .env.production .env
          # Build
          echo "Starting build..."
          npm run build
          # Verify build output
          echo "Build completed. Checking build directory..."
          ls -la build/ | head -10
        env:
          CI: false
          NODE_OPTIONS: --max-old-space-size=4096
          GENERATE_SOURCEMAP: false
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
