name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install --legacy-peer-deps
          echo "Dependencies installed successfully"
        
      - name: Build with production env
        run: |
          echo "Copying production env..."
          cp .env.production .env
          echo "Building application..."
          npm run build
          echo "Build completed successfully"
          echo "Checking build output..."
          ls -la build/
        env:
          CI: false
          NODE_OPTIONS: --max-old-space-size=4096
          GENERATE_SOURCEMAP: false
          
      - name: Install gh-pages
        run: |
          echo "Installing gh-pages..."
          npm install -g gh-pages@6.1.1
          echo "gh-pages installed"
          
      - name: Deploy to gh-pages
        run: |
          echo "Configuring git..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "Setting remote URL..."
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          echo "Deploying to gh-pages..."
          gh-pages -d build --no-history
          echo "Deployment completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
